name: Deploy Hugo Site

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - main  # Change to 'master' if your branch is named that
    # The Magic Trigger: This workflow ONLY runs if files in the 'blog' folder change
    paths:
      - 'blog/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive # Fetch Hugo themes (true for most themes)
          fetch-depth: 0        # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.146.0' # Force the version your theme needs
          extended: true          # Download the extended version (usually required)

      - name: Build with Hugo
        # We assume your hugo site is in the 'blog' directory
        run: |
          cd blog
          hugo --minify

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # This must point to where Hugo generated the HTML
          # Since we ran hugo inside 'blog', the output is 'blog/public'
          path: ./blog/public

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
